"""phase one schema, fifteen tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-03 13:48:53.113524
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cp_group',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('group_limit_pence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cp_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cp_group_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('oracle_balance',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('balance_pence', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.String(length=10), nullable=False),
    sa.Column('received_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oracle_balance', schema=None) as batch_op:
        batch_op.create_index('ix_oracle_balance_asof', ['tenant_id', 'as_of_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_oracle_balance_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('policy_version',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('effective_from', sa.String(length=10), nullable=False),
    sa.Column('superseded_at', sa.String(length=30), nullable=True),
    sa.Column('concentration_cap_bp', sa.Integer(), nullable=False),
    sa.Column('threshold_analyst_pence', sa.Integer(), nullable=False),
    sa.Column('threshold_hot_pence', sa.Integer(), nullable=False),
    sa.Column('enforcement', sa.String(length=24), nullable=False),
    sa.Column('fx_add_on_bp', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=False),
    sa.CheckConstraint("enforcement in ('HARD_BLOCK','WARN_WITH_OVERRIDE')", name='ck_policy_enforcement'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_version_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_policy_current', ['tenant_id'], unique=True, sqlite_where=sa.text('superseded_at IS NULL'))

    op.create_table('rating_band',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('max_limit_pence', sa.Integer(), nullable=False),
    sa.Column('max_tenor_months', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rating', name='ux_rating_band')
    )
    with op.batch_alter_table('rating_band', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_band_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('system_clock',
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('today_date', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('counterparty',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('group_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_entity_identifier', sa.String(length=40), nullable=True),
    sa.Column('group_parent_name', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('rating_status', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('verified_by', sa.String(length=120), nullable=True),
    sa.Column('verified_at', sa.String(length=30), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.String(length=30), nullable=True),
    sa.Column('activated_at', sa.String(length=30), nullable=True),
    sa.CheckConstraint("rating_status in ('STABLE','WATCH','NEGATIVE','POSITIVE')", name='ck_counterparty_rating_status'),
    sa.CheckConstraint("status in ('DRAFT','VERIFIED','APPROVED','ACTIVE','SUSPENDED')", name='ck_counterparty_status'),
    sa.ForeignKeyConstraint(['group_id'], ['cp_group.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('counterparty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterparty_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparty_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('counterparty_instrument',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.CheckConstraint("instrument in ('DEPOSIT','FX_FORWARD','MMF','GILT')", name='ck_cp_instrument'),
    sa.CheckConstraint('enabled in (0,1)', name='ck_cp_instrument_enabled'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('counterparty_id', 'instrument', name='ux_cp_instrument')
    )
    with op.batch_alter_table('counterparty_instrument', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_counterparty_instrument_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_counterparty_instrument_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('cp_limit',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('max_tenor_months', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('effective_from', sa.String(length=10), nullable=False),
    sa.Column('superseded_at', sa.String(length=30), nullable=True),
    sa.Column('superseded_by_event', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=False),
    sa.Column('approved_at', sa.String(length=30), nullable=False),
    sa.CheckConstraint("source in ('BAND','MANUAL')", name='ck_limit_source'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cp_limit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cp_limit_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cp_limit_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_limit_current', ['counterparty_id'], unique=True, sqlite_where=sa.text('superseded_at IS NULL'))

    op.create_table('rating_event',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('previous_rating', sa.String(length=8), nullable=False),
    sa.Column('new_rating', sa.String(length=8), nullable=False),
    sa.Column('previous_status', sa.String(length=12), nullable=False),
    sa.Column('new_status', sa.String(length=12), nullable=False),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('policy_version_id', sa.String(length=40), nullable=True),
    sa.Column('positions_tested', sa.Integer(), nullable=False),
    sa.Column('breaches_raised', sa.Integer(), nullable=False),
    sa.Column('recorded_by', sa.String(length=120), nullable=False),
    sa.Column('recorded_at', sa.String(length=30), nullable=False),
    sa.CheckConstraint("action in ('UPGRADE','DOWNGRADE','WATCH','AFFIRM')", name='ck_rating_action'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_version.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_event_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_event_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('deal',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('principal_pence', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate_bp', sa.Integer(), nullable=False),
    sa.Column('tenor_months', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('value_date', sa.String(length=10), nullable=False),
    sa.Column('maturity_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('capture_source', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('required_approver', sa.String(length=24), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.String(length=30), nullable=True),
    sa.Column('limit_id_at_booking', sa.String(length=40), nullable=True),
    sa.Column('policy_version_id', sa.String(length=40), nullable=True),
    sa.Column('check_run_id', sa.String(length=40), nullable=True),
    sa.Column('instructed_at', sa.String(length=30), nullable=True),
    sa.Column('closed_at', sa.String(length=30), nullable=True),
    sa.CheckConstraint("capture_source in ('KEYED','FROM_CONFIRMATION')", name='ck_deal_capture_source'),
    sa.CheckConstraint("instrument in ('DEPOSIT','FX_FORWARD','MMF','GILT')", name='ck_deal_instrument'),
    sa.CheckConstraint("status in ('PROPOSED','BLOCKED','ACTIVE','MATURED','CLOSED','CANCELLED')", name='ck_deal_status'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['limit_id_at_booking'], ['cp_limit.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_version.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index('ix_deal_cp_active', ['counterparty_id', 'status'], unique=False)
        batch_op.create_index('ix_deal_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('breach',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('deal_id', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('limit_id', sa.String(length=40), nullable=True),
    sa.Column('rating_event_id', sa.String(length=40), nullable=True),
    sa.Column('original_check_run_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('response', sa.String(length=20), nullable=True),
    sa.Column('response_reason', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.String(length=120), nullable=True),
    sa.Column('responded_at', sa.String(length=30), nullable=True),
    sa.Column('raised_at', sa.String(length=30), nullable=False),
    sa.CheckConstraint("response is null or response in ('HOLD_TO_MATURITY','BREAK_EARLY','SEEK_RATIFICATION','REDUCE_ON_ROLL')", name='ck_breach_response'),
    sa.CheckConstraint("status in ('OPEN','RESPONDED')", name='ck_breach_status'),
    sa.CheckConstraint("type in ('AMOUNT','TENOR','GROUP','CONCENTRATION','RATING')", name='ck_breach_type'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['limit_id'], ['cp_limit.id'], ),
    sa.ForeignKeyConstraint(['rating_event_id'], ['rating_event.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breach', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breach_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breach_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breach_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('check_run',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('deal_id', sa.String(length=40), nullable=True),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('as_of_date', sa.String(length=10), nullable=False),
    sa.Column('limit_id', sa.String(length=40), nullable=True),
    sa.Column('policy_version_id', sa.String(length=40), nullable=False),
    sa.Column('outcome', sa.String(length=12), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('measured_pence', sa.Integer(), nullable=True),
    sa.Column('measurement_basis', sa.Text(), nullable=True),
    sa.Column('required_approver', sa.String(length=24), nullable=True),
    sa.Column('inputs_json', sa.Text(), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.CheckConstraint("outcome in ('PASS','FAIL','OVERRIDDEN')", name='ck_check_run_outcome'),
    sa.CheckConstraint("purpose in ('CHECK','BOOKING','RETEST','CORRECTION','ADVISORY_CANDIDATE','ADVISORY_VALIDATION')", name='ck_check_run_purpose'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['limit_id'], ['cp_limit.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_version.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('check_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_run_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_run_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_run_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('oracle_instruction',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('deal_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('value_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('oracle_reference', sa.String(length=60), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.String(length=30), nullable=True),
    sa.CheckConstraint("status in ('PENDING','SENT','ACKNOWLEDGED','FAILED')", name='ck_instruction_status'),
    sa.CheckConstraint("type in ('PAYMENT_REQUEST','EXPECTED_INBOUND')", name='ck_instruction_type'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oracle_instruction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oracle_instruction_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('exception_item',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('deal_id', sa.String(length=40), nullable=True),
    sa.Column('confirmation_id', sa.String(length=40), nullable=True),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('cause', sa.String(length=24), nullable=False),
    sa.Column('reason_code', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('check_run_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('raised_at', sa.String(length=30), nullable=False),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.Column('resolved_at', sa.String(length=30), nullable=True),
    sa.CheckConstraint("cause in ('LIMIT_FAILURE','CONFIRMATION_MISMATCH')", name='ck_exception_cause'),
    sa.CheckConstraint("resolution is null or resolution in ('RESIZED','REROUTED','OVERRIDDEN','CANCELLED','CORRECTED','CHALLENGED')", name='ck_exception_resolution'),
    sa.CheckConstraint("status in ('OPEN','RESOLVED')", name='ck_exception_status'),
    sa.ForeignKeyConstraint(['check_run_id'], ['check_run.id'], ),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exception_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exception_item_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exception_item_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_queue_open', ['tenant_id', 'status', 'cause'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exception_item', schema=None) as batch_op:
        batch_op.drop_index('ix_queue_open')
        batch_op.drop_index(batch_op.f('ix_exception_item_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_exception_item_deal_id'))

    op.drop_table('exception_item')
    with op.batch_alter_table('oracle_instruction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oracle_instruction_tenant_id'))

    op.drop_table('oracle_instruction')
    with op.batch_alter_table('check_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_run_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_check_run_deal_id'))
        batch_op.drop_index(batch_op.f('ix_check_run_counterparty_id'))

    op.drop_table('check_run')
    with op.batch_alter_table('breach', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breach_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_breach_deal_id'))
        batch_op.drop_index(batch_op.f('ix_breach_counterparty_id'))

    op.drop_table('breach')
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_tenant_id'))
        batch_op.drop_index('ix_deal_status')
        batch_op.drop_index('ix_deal_cp_active')
        batch_op.drop_index(batch_op.f('ix_deal_counterparty_id'))

    op.drop_table('deal')
    with op.batch_alter_table('rating_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_event_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_rating_event_counterparty_id'))

    op.drop_table('rating_event')
    with op.batch_alter_table('cp_limit', schema=None) as batch_op:
        batch_op.drop_index('ux_limit_current', sqlite_where=sa.text('superseded_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_cp_limit_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_cp_limit_counterparty_id'))

    op.drop_table('cp_limit')
    with op.batch_alter_table('counterparty_instrument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterparty_instrument_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_counterparty_instrument_counterparty_id'))

    op.drop_table('counterparty_instrument')
    with op.batch_alter_table('counterparty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_counterparty_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_counterparty_group_id'))

    op.drop_table('counterparty')
    op.drop_table('system_clock')
    with op.batch_alter_table('rating_band', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_band_tenant_id'))

    op.drop_table('rating_band')
    with op.batch_alter_table('policy_version', schema=None) as batch_op:
        batch_op.drop_index('ux_policy_current', sqlite_where=sa.text('superseded_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_policy_version_tenant_id'))

    op.drop_table('policy_version')
    with op.batch_alter_table('oracle_balance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oracle_balance_tenant_id'))
        batch_op.drop_index('ix_oracle_balance_asof')

    op.drop_table('oracle_balance')
    with op.batch_alter_table('cp_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cp_group_tenant_id'))

    op.drop_table('cp_group')
    op.drop_table('tenant')
    # ### end Alembic commands ###
