"""identity, users and memberships

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-03 16:09:49.905573
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('disabled_at', sa.String(length=30), nullable=True),
    sa.CheckConstraint("status in ('ACTIVE','DISABLED')", name='ck_user_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='ux_user_email')
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('membership',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('granted_by', sa.String(length=120), nullable=False),
    sa.Column('granted_at', sa.String(length=30), nullable=False),
    sa.Column('revoked_at', sa.String(length=30), nullable=True),
    sa.CheckConstraint("role in ('ANALYST','HEAD_OF_TREASURY','CFO','OPERATOR','AUDITOR')", name='ck_membership_role'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membership_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ux_membership_live', ['user_id', 'role'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_index('ux_membership_live', sqlite_where=sa.text('revoked_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_membership_user_id'))
        batch_op.drop_index(batch_op.f('ix_membership_tenant_id'))

    op.drop_table('membership')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_tenant_id'))

    op.drop_table('app_user')
    # ### end Alembic commands ###
