"""identity, user identifiers on every evidence record

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-03 16:13:36.445676
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responded_by_user_id', sa.String(length=40), nullable=True))
        batch_op.create_foreign_key('fk_breach_responded_by_user', 'app_user', ['responded_by_user_id'], ['id'])

    with op.batch_alter_table('check_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=40), nullable=True))
        batch_op.create_foreign_key('fk_check_run_created_by_user', 'app_user', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('counterparty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('activated_by_user_id', sa.String(length=40), nullable=True))
        batch_op.create_foreign_key('fk_counterparty_activated_by_user', 'app_user', ['activated_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_counterparty_created_by_user', 'app_user', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('cp_limit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by_user_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('recorded_by_user_id', sa.String(length=40), nullable=True))
        batch_op.create_foreign_key('fk_cp_limit_recorded_by_user', 'app_user', ['recorded_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_cp_limit_approved_by_user', 'app_user', ['approved_by_user_id'], ['id'])

    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('approved_by_user_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('approved_role', sa.String(length=24), nullable=True))
        batch_op.create_foreign_key('fk_deal_approved_by_user', 'app_user', ['approved_by_user_id'], ['id'])
        batch_op.create_foreign_key('fk_deal_created_by_user', 'app_user', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('exception_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolved_by_user_id', sa.String(length=40), nullable=True))
        batch_op.create_foreign_key('fk_exception_resolved_by_user', 'app_user', ['resolved_by_user_id'], ['id'])

    with op.batch_alter_table('oracle_instruction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=40), nullable=True))
        batch_op.create_foreign_key('fk_instruction_created_by_user', 'app_user', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('rating_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_by_user_id', sa.String(length=40), nullable=True))
        batch_op.create_foreign_key('fk_rating_event_recorded_by_user', 'app_user', ['recorded_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rating_event_recorded_by_user', type_='foreignkey')
        batch_op.drop_column('recorded_by_user_id')

    with op.batch_alter_table('oracle_instruction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_instruction_created_by_user', type_='foreignkey')
        batch_op.drop_column('created_by_user_id')

    with op.batch_alter_table('exception_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exception_resolved_by_user', type_='foreignkey')
        batch_op.drop_column('resolved_by_user_id')

    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deal_created_by_user', type_='foreignkey')
        batch_op.drop_constraint('fk_deal_approved_by_user', type_='foreignkey')
        batch_op.drop_column('approved_role')
        batch_op.drop_column('approved_by_user_id')
        batch_op.drop_column('created_by_user_id')

    with op.batch_alter_table('cp_limit', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cp_limit_approved_by_user', type_='foreignkey')
        batch_op.drop_constraint('fk_cp_limit_recorded_by_user', type_='foreignkey')
        batch_op.drop_column('recorded_by_user_id')
        batch_op.drop_column('approved_by_user_id')

    with op.batch_alter_table('counterparty', schema=None) as batch_op:
        batch_op.drop_constraint('fk_counterparty_created_by_user', type_='foreignkey')
        batch_op.drop_constraint('fk_counterparty_activated_by_user', type_='foreignkey')
        batch_op.drop_column('activated_by_user_id')
        batch_op.drop_column('created_by_user_id')

    with op.batch_alter_table('check_run', schema=None) as batch_op:
        batch_op.drop_constraint('fk_check_run_created_by_user', type_='foreignkey')
        batch_op.drop_column('created_by_user_id')

    with op.batch_alter_table('breach', schema=None) as batch_op:
        batch_op.drop_constraint('fk_breach_responded_by_user', type_='foreignkey')
        batch_op.drop_column('responded_by_user_id')

    # ### end Alembic commands ###
