"""accounting and the advisory layer

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-03 16:31:47.473664
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_line',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('as_of', sa.String(length=10), nullable=False),
    sa.Column('forecast_date', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=120), nullable=True),
    sa.Column('received_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecast_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecast_line_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_forecast_window', ['tenant_id', 'forecast_date'], unique=False)

    op.create_table('investment_policy',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('effective_from', sa.String(length=10), nullable=False),
    sa.Column('superseded_at', sa.String(length=30), nullable=True),
    sa.Column('liquidity_buffer_pence', sa.Integer(), nullable=False),
    sa.Column('buffer_horizon_days', sa.Integer(), nullable=False),
    sa.Column('priority_order', sa.String(length=60), nullable=False),
    sa.Column('model_enabled', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=False),
    sa.Column('recorded_by_user_id', sa.String(length=40), nullable=True),
    sa.CheckConstraint('model_enabled in (0,1)', name='ck_investment_model_enabled'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['app_user.id'], name='fk_investment_policy_recorded_by'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investment_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investment_policy_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_investment_policy_current', ['tenant_id'], unique=True, sqlite_where=sa.text('superseded_at IS NULL'))

    op.create_table('advisory_run',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('as_of', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.String(length=30), nullable=False),
    sa.Column('finished_at', sa.String(length=30), nullable=True),
    sa.Column('policy_id', sa.String(length=40), nullable=False),
    sa.Column('gap_type', sa.String(length=24), nullable=False),
    sa.Column('gap_amount_minor', sa.Integer(), nullable=True),
    sa.Column('gap_currency', sa.String(length=3), nullable=True),
    sa.Column('gap_date', sa.String(length=10), nullable=True),
    sa.Column('model_enabled', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=True),
    sa.Column('outcome', sa.String(length=28), nullable=False),
    sa.CheckConstraint("gap_type in ('CASH_SURPLUS','CASH_SHORTFALL','LADDER_GAP','CURRENCY_UNCOVERED','NONE')", name='ck_run_gap_type'),
    sa.CheckConstraint("outcome in ('NO_GAP','MODEL_ACCEPTED','MODEL_REJECTED_FALLBACK','RULE_ONLY','NO_CANDIDATES')", name='ck_run_outcome'),
    sa.ForeignKeyConstraint(['policy_id'], ['investment_policy.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisory_run', schema=None) as batch_op:
        batch_op.create_index('ix_advisory_run_asof', ['tenant_id', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisory_run_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('currency_cover_target',
    sa.Column('policy_id', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('target_cover_bp', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['investment_policy.id'], ),
    sa.PrimaryKeyConstraint('policy_id', 'currency')
    )
    op.create_table('ladder_target',
    sa.Column('policy_id', sa.String(length=40), nullable=False),
    sa.Column('bucket', sa.String(length=10), nullable=False),
    sa.Column('target_share_bp', sa.Integer(), nullable=False),
    sa.Column('minimum_pence', sa.Integer(), nullable=False),
    sa.CheckConstraint("bucket in ('0_3M','3_6M','6_12M','OVER_12M')", name='ck_ladder_bucket'),
    sa.ForeignKeyConstraint(['policy_id'], ['investment_policy.id'], ),
    sa.PrimaryKeyConstraint('policy_id', 'bucket')
    )
    op.create_table('candidate',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('tenor_months', sa.Integer(), nullable=False),
    sa.Column('indicative_rate_bp', sa.Integer(), nullable=False),
    sa.Column('score_bp', sa.Integer(), nullable=False),
    sa.Column('excluded', sa.Integer(), nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.CheckConstraint('excluded in (0,1)', name='ck_candidate_excluded'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['advisory_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_index('ix_candidate_run', ['run_id', 'excluded', 'rank'], unique=False)

    op.create_table('validation_result',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('test', sa.String(length=24), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.CheckConstraint("test in ('ID_IS_REAL','CHECKS_RERUN_CLEAN','FIGURES_AGREE')", name='ck_validation_test'),
    sa.CheckConstraint('passed in (0,1)', name='ck_validation_passed'),
    sa.ForeignKeyConstraint(['run_id'], ['advisory_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accrual',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('deal_id', sa.String(length=40), nullable=False),
    sa.Column('accrual_date', sa.String(length=10), nullable=False),
    sa.Column('day_count', sa.Integer(), nullable=False),
    sa.Column('rate_bp', sa.Integer(), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('cumulative_pence', sa.Integer(), nullable=False),
    sa.Column('reversal_of', sa.String(length=40), nullable=True),
    sa.Column('amendment_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accrual', schema=None) as batch_op:
        batch_op.create_index('ix_accrual_date', ['tenant_id', 'accrual_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_accrual_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accrual_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ux_accrual_day', ['deal_id', 'accrual_date'], unique=True, sqlite_where=sa.text('reversal_of IS NULL'))

    op.create_table('recommendation',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('candidate_id', sa.String(length=40), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('alternatives_json', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=True),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decided_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('decided_at', sa.String(length=30), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('deal_id', sa.String(length=40), nullable=True),
    sa.CheckConstraint("decision is null or decision in ('ACCEPTED','EDITED','REJECTED','EXPIRED')", name='ck_rec_decision'),
    sa.CheckConstraint("source in ('MODEL','RULE_FALLBACK')", name='ck_rec_source'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['app_user.id'], name='fk_recommendation_decided_by'),
    sa.ForeignKeyConstraint(['run_id'], ['advisory_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('deal_id', sa.String(length=40), nullable=False),
    sa.Column('accrual_id', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('debit_account', sa.String(length=40), nullable=False),
    sa.Column('credit_account', sa.String(length=40), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('posted_at', sa.String(length=30), nullable=True),
    sa.Column('oracle_reference', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status in ('BUILT','POSTED','FAILED')", name='ck_journal_status'),
    sa.CheckConstraint("type in ('ACCRUAL','SETTLEMENT','REVALUATION','REVERSAL')", name='ck_journal_type'),
    sa.ForeignKeyConstraint(['accrual_id'], ['accrual.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index('ix_journal_period', ['tenant_id', 'period', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_tenant_id'))
        batch_op.drop_index('ix_journal_period')
        batch_op.drop_index(batch_op.f('ix_journal_deal_id'))

    op.drop_table('journal')
    op.drop_table('recommendation')
    with op.batch_alter_table('accrual', schema=None) as batch_op:
        batch_op.drop_index('ux_accrual_day', sqlite_where=sa.text('reversal_of IS NULL'))
        batch_op.drop_index(batch_op.f('ix_accrual_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_accrual_deal_id'))
        batch_op.drop_index('ix_accrual_date')

    op.drop_table('accrual')
    op.drop_table('validation_result')
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_index('ix_candidate_run')

    op.drop_table('candidate')
    op.drop_table('ladder_target')
    op.drop_table('currency_cover_target')
    with op.batch_alter_table('advisory_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisory_run_tenant_id'))
        batch_op.drop_index('ix_advisory_run_asof')

    op.drop_table('advisory_run')
    with op.batch_alter_table('investment_policy', schema=None) as batch_op:
        batch_op.drop_index('ux_investment_policy_current', sqlite_where=sa.text('superseded_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_investment_policy_tenant_id'))

    op.drop_table('investment_policy')
    with op.batch_alter_table('forecast_line', schema=None) as batch_op:
        batch_op.drop_index('ix_forecast_window')
        batch_op.drop_index(batch_op.f('ix_forecast_line_tenant_id'))

    op.drop_table('forecast_line')
    # ### end Alembic commands ###
