"""the deal lifecycle and currency risk

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-03 17:09:20.427893
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_statement_line',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('value_date', sa.String(length=10), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=True),
    sa.Column('received_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_statement_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_statement_line_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_statement_line', ['tenant_id', 'value_date'], unique=False)

    op.create_table('fx_rate',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('pair', sa.String(length=6), nullable=False),
    sa.Column('rate_e8', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'pair', 'as_of', name='ux_fx_rate_day')
    )
    with op.batch_alter_table('fx_rate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_rate_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('currency_exposure',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('expected_date', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_reference', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.Column('settled_at', sa.String(length=30), nullable=True),
    sa.CheckConstraint("direction in ('PAYABLE','RECEIVABLE')", name='ck_currency_direction'),
    sa.CheckConstraint("source in ('CONTRACT','PURCHASE_ORDER','INVOICE','FORECAST')", name='ck_currency_source'),
    sa.CheckConstraint("status in ('IDENTIFIED','PARTIALLY_COVERED','COVERED','SETTLED')", name='ck_currency_status'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name='fk_currency_exposure_created_by'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('currency_exposure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currency_exposure_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_currency_exposure_window', ['tenant_id', 'currency', 'expected_date'], unique=False)

    op.create_table('amendment',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('deal_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=False),
    sa.Column('new_principal_pence', sa.Integer(), nullable=True),
    sa.Column('new_rate_bp', sa.Integer(), nullable=True),
    sa.Column('new_maturity_date', sa.String(length=10), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('raised_by', sa.String(length=120), nullable=False),
    sa.Column('raised_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('raised_at', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('applied_at', sa.String(length=30), nullable=True),
    sa.CheckConstraint("status in ('RAISED','APPLIED','REJECTED')", name='ck_amendment_status'),
    sa.CheckConstraint("type in ('BREAK','ROLL','PARTIAL_DRAWDOWN','CORRECTION')", name='ck_amendment_type'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['raised_by_user_id'], ['app_user.id'], name='fk_amendment_raised_by'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amendment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amendment_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_amendment_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('confirmation',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('deal_id', sa.String(length=40), nullable=True),
    sa.Column('counterparty_id', sa.String(length=40), nullable=True),
    sa.Column('message_type', sa.String(length=16), nullable=False),
    sa.Column('reference', sa.String(length=60), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('principal_pence', sa.Integer(), nullable=False),
    sa.Column('rate_bp', sa.Integer(), nullable=False),
    sa.Column('value_date', sa.String(length=10), nullable=False),
    sa.Column('maturity_date', sa.String(length=10), nullable=True),
    sa.Column('received_at', sa.String(length=30), nullable=False),
    sa.Column('match_status', sa.String(length=12), nullable=False),
    sa.Column('matched_at', sa.String(length=30), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.CheckConstraint("match_status in ('UNMATCHED','MATCHED','MISMATCHED','DISPUTED')", name='ck_confirmation_match_status'),
    sa.CheckConstraint("message_type in ('MT300','MT320','MT535','MT536','BROKER_NOTE','DOCUMENT')", name='ck_confirmation_message_type'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'counterparty_id', 'reference', name='ux_confirmation_reference')
    )
    with op.batch_alter_table('confirmation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confirmation_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_confirmation_unmatched', ['tenant_id', 'match_status'], unique=False, sqlite_where=sa.text('deal_id IS NULL'))

    op.create_table('hedge_link',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('currency_exposure_id', sa.String(length=40), nullable=False),
    sa.Column('deal_id', sa.String(length=40), nullable=False),
    sa.Column('covered_amount_minor', sa.Integer(), nullable=False),
    sa.Column('linked_by', sa.String(length=120), nullable=False),
    sa.Column('linked_at', sa.String(length=30), nullable=False),
    sa.Column('unlinked_at', sa.String(length=30), nullable=True),
    sa.Column('unlink_reason', sa.String(length=24), nullable=True),
    sa.Column('unlinked_by', sa.String(length=120), nullable=True),
    sa.CheckConstraint("unlink_reason is null or unlink_reason in ('ROLLED','CLOSED_EARLY','EXPOSURE_CANCELLED','REALLOCATED')", name='ck_hedge_unlink_reason'),
    sa.ForeignKeyConstraint(['currency_exposure_id'], ['currency_exposure.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hedge_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hedge_link_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_hedge_live', ['currency_exposure_id'], unique=False, sqlite_where=sa.text('unlinked_at IS NULL'))

    op.create_table('settlement',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('deal_id', sa.String(length=40), nullable=False),
    sa.Column('expected_principal_pence', sa.Integer(), nullable=False),
    sa.Column('expected_interest_pence', sa.Integer(), nullable=False),
    sa.Column('confirmed_amount_pence', sa.Integer(), nullable=True),
    sa.Column('statement_amount_pence', sa.Integer(), nullable=True),
    sa.Column('statement_line_id', sa.String(length=40), nullable=True),
    sa.Column('match_status', sa.String(length=12), nullable=False),
    sa.Column('break_detail', sa.Text(), nullable=True),
    sa.Column('settled_by', sa.String(length=120), nullable=True),
    sa.Column('settled_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('closed_at', sa.String(length=30), nullable=True),
    sa.CheckConstraint("match_status in ('PENDING','AGREED','BREAK')", name='ck_settlement_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deal.id'], ),
    sa.ForeignKeyConstraint(['settled_by_user_id'], ['app_user.id'], name='fk_settlement_settled_by'),
    sa.ForeignKeyConstraint(['statement_line_id'], ['bank_statement_line.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', name='ux_settlement_deal')
    )
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('match_difference',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('confirmation_id', sa.String(length=40), nullable=False),
    sa.Column('field_name', sa.String(length=30), nullable=False),
    sa.Column('keyed_value', sa.String(length=60), nullable=False),
    sa.Column('confirmed_value', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['confirmation_id'], ['confirmation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_difference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_difference_confirmation_id'), ['confirmation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_difference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_difference_confirmation_id'))

    op.drop_table('match_difference')
    with op.batch_alter_table('settlement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_tenant_id'))

    op.drop_table('settlement')
    with op.batch_alter_table('hedge_link', schema=None) as batch_op:
        batch_op.drop_index('ix_hedge_live', sqlite_where=sa.text('unlinked_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_hedge_link_tenant_id'))

    op.drop_table('hedge_link')
    with op.batch_alter_table('confirmation', schema=None) as batch_op:
        batch_op.drop_index('ix_confirmation_unmatched', sqlite_where=sa.text('deal_id IS NULL'))
        batch_op.drop_index(batch_op.f('ix_confirmation_tenant_id'))

    op.drop_table('confirmation')
    with op.batch_alter_table('amendment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amendment_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_amendment_deal_id'))

    op.drop_table('amendment')
    with op.batch_alter_table('currency_exposure', schema=None) as batch_op:
        batch_op.drop_index('ix_currency_exposure_window')
        batch_op.drop_index(batch_op.f('ix_currency_exposure_tenant_id'))

    op.drop_table('currency_exposure')
    with op.batch_alter_table('fx_rate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rate_tenant_id'))

    op.drop_table('fx_rate')
    with op.batch_alter_table('bank_statement_line', schema=None) as batch_op:
        batch_op.drop_index('ix_statement_line')
        batch_op.drop_index(batch_op.f('ix_bank_statement_line_tenant_id'))

    op.drop_table('bank_statement_line')
    # ### end Alembic commands ###
