"""the accrual day index excludes amendment rows

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-03 17:20:50.019313

Document 1 writes the predicate as `reversal_of IS NULL` alone. That admits
one original per deal per day and nothing else, so a correction cannot be
reposted: the reversal is written, and the repost at the new terms collides
with the row it just reversed. The predicate is widened to exclude amendment
rows as well, which keeps the guarantee that matters -- one unamended
original per day -- while letting a correction land.

Autogenerate does not compare index predicates, so this body is written by
hand. The empty autogenerated version of this file was the defect: every
database created by `create_all` had the new predicate and every migrated
database kept the old one, which is the worst of the two.
"""
from typing import Sequence, Union

from alembic import op


revision: str = '0007'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NAME = "ux_accrual_day"
NEW = "reversal_of IS NULL AND amendment_id IS NULL"
OLD = "reversal_of IS NULL"


def upgrade() -> None:
    # Raw SQL rather than op.create_index, because the predicate has to
    # survive verbatim and the dialect keyword differs between SQLite and
    # PostgreSQL. This is the one place the two are the same string.
    op.drop_index(NAME, table_name="accrual")
    op.execute(
        f"CREATE UNIQUE INDEX {NAME} ON accrual (deal_id, accrual_date) "
        f"WHERE {NEW}"
    )


def downgrade() -> None:
    op.drop_index(NAME, table_name="accrual")
    op.execute(
        f"CREATE UNIQUE INDEX {NAME} ON accrual (deal_id, accrual_date) "
        f"WHERE {OLD}"
    )
