"""add news item table for credit signals

Revision ID: 9628e5ff4421
Revises: 0008
Create Date: 2026-09-04 11:07:00.938554
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0009'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_item',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('counterparty_id', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('headline', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published_at', sa.String(length=10), nullable=False),
    sa.Column('ingested_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparty.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_item_counterparty_id'), ['counterparty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_item_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_item_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_news_item_counterparty_id'))

    op.drop_table('news_item')
    # ### end Alembic commands ###
