"""admin page: audit_event table + user last_signed_in + admin roles

Revision ID: 29704f3ee889
Revises: 0009
Create Date: 2026-09-18 11:45:40.386283
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '29704f3ee889'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Order matters — expand app_user first so the audit_event FK to it
    # lands cleanly. SQLite batch_alter recreates the referenced table
    # under the hood and gets confused if audit_event already points at it.
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_signed_in_at', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('invited_by_user_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('invited_at', sa.String(length=30), nullable=True))

    op.create_table('audit_event',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.String(length=30), nullable=False),
    sa.Column('actor_user_id', sa.String(length=40), nullable=True),
    sa.Column('actor_display', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=60), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], name='fk_audit_actor_user'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_event', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_event_occurred_at', 'audit_event', ['occurred_at'], unique=False)
    op.create_index('ix_audit_event_tenant_id', 'audit_event', ['tenant_id'], unique=False)
    op.create_index('ix_audit_subject', 'audit_event', ['subject_type', 'subject_id'], unique=False)

    # Widen the membership.role CheckConstraint to admit the two new
    # roles introduced by the persona pages (ADMIN, COMPLIANCE_OFFICER).
    # SQLite has no ALTER CONSTRAINT — batch_alter recreates the table.
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.drop_constraint('ck_membership_role', type_='check')
        batch_op.create_check_constraint(
            'ck_membership_role',
            "role in ('ANALYST','HEAD_OF_TREASURY','CFO','OPERATOR','AUDITOR',"
            "'ADMIN','COMPLIANCE_OFFICER')",
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_column('invited_at')
        batch_op.drop_column('invited_by_user_id')
        batch_op.drop_column('last_signed_in_at')

    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_subject')
        batch_op.drop_index(batch_op.f('ix_audit_event_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_occurred_at'))
        batch_op.drop_index('ix_audit_actor')

    op.drop_table('audit_event')
    # ### end Alembic commands ###
