"""phase D: access_change_request table

Revision ID: 694ad4b80e75
Revises: c2d259c21e3e
Create Date: 2026-09-18 13:09:28.058763
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '694ad4b80e75'
down_revision: Union[str, None] = 'c2d259c21e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_change_request',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('subject_type', sa.String(length=24), nullable=False),
    sa.Column('subject_id', sa.String(length=40), nullable=False),
    sa.Column('change_type', sa.String(length=24), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=40), nullable=False),
    sa.Column('requested_by_display', sa.String(length=120), nullable=False),
    sa.Column('requested_at', sa.String(length=30), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(length=40), nullable=True),
    sa.Column('reviewed_by_display', sa.String(length=120), nullable=True),
    sa.Column('reviewed_at', sa.String(length=30), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status in ('PENDING','APPROVED','REJECTED','WITHDRAWN')", name='ck_access_req_status'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['app_user.id'], name='fk_access_req_requester'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['app_user.id'], name='fk_access_req_reviewer'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_change_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_change_request_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_change_request_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_change_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_change_request_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_access_change_request_subject_id'))

    op.drop_table('access_change_request')
    # ### end Alembic commands ###
