"""phase B.2: legal_entity_id on deal and currency_exposure

Revision ID: 967550612047
Revises: a7958fe8d700
Create Date: 2026-09-18 12:33:01.777855
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '967550612047'
down_revision: Union[str, None] = 'a7958fe8d700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('currency_exposure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_entity_id', sa.String(length=40), nullable=True))

    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_entity_id', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal', schema=None) as batch_op:
        batch_op.drop_column('legal_entity_id')

    with op.batch_alter_table('currency_exposure', schema=None) as batch_op:
        batch_op.drop_column('legal_entity_id')

    # ### end Alembic commands ###
