"""admin phase B: legal_entity + user_entity_scope

Revision ID: a7958fe8d700
Revises: 29704f3ee889
Create Date: 2026-09-18 12:23:25.544305
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a7958fe8d700'
down_revision: Union[str, None] = '29704f3ee889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_entity',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.CheckConstraint("status in ('ACTIVE','ARCHIVED')", name='ck_legal_entity_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='ux_legal_entity_code')
    )
    with op.batch_alter_table('legal_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_entity_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('user_entity_scope',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('legal_entity_id', sa.String(length=40), nullable=True),
    sa.Column('granted_by', sa.String(length=120), nullable=False),
    sa.Column('granted_at', sa.String(length=30), nullable=False),
    sa.Column('revoked_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entity.id'], name='fk_scope_entity'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name='fk_scope_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_entity_scope', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_entity_scope_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_entity_scope_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ux_scope_live', ['user_id', 'legal_entity_id'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_entity_scope', schema=None) as batch_op:
        batch_op.drop_index('ux_scope_live', sqlite_where=sa.text('revoked_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_user_entity_scope_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_entity_scope_tenant_id'))

    op.drop_table('user_entity_scope')
    with op.batch_alter_table('legal_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_entity_tenant_id'))

    op.drop_table('legal_entity')
    # ### end Alembic commands ###
