"""phase C: activation_token table

Revision ID: c2d259c21e3e
Revises: 967550612047
Create Date: 2026-09-18 12:55:12.807593
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c2d259c21e3e'
down_revision: Union[str, None] = '967550612047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_token',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('tenant_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.String(length=30), nullable=False),
    sa.Column('consumed_at', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=False),
    sa.CheckConstraint("purpose in ('INVITE','RESET')", name='ck_activation_purpose'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name='fk_activation_user'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activation_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activation_token_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activation_token_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_activation_token_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activation_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activation_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_activation_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_activation_token_tenant_id'))

    op.drop_table('activation_token')
    # ### end Alembic commands ###
